apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: ditt-nav-arbeidsgiver
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - '{{{ingress}}}'
  liveness:
    path: /min-side-arbeidsgiver/internal/isAlive
    initialDelay: 20
  readiness:
    path: /min-side-arbeidsgiver/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /min-side-arbeidsgiver/internal/metrics
  vault:
    enabled: false
  webproxy: false
  idporten:
    enabled: {{ idporten }}
  envFrom:
    - secret: innsyn-aareg
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: API_GATEWAY
      value: http://min-side-arbeidsgiver-api.fager
    - name: LOGIN_URL
      value: '{{{selvbetjening-login-url}}}'
    - name: DECORATOR_EXTERNAL_URL
      value: '{{{decorator-external-url}}}'
    - name: PROXY_LOG_LEVEL
      value: 'debug'
    - name: BRUKER_API_URL
      value: '{{{bruker-api-url}}}'
    - name: GIT_COMMIT
      value: {{commit}}
    - name: ARBEIDSFORHOLD_DOMAIN
      value: '{{{arbeidsforhold-domain}}}'
  accessPolicy:
    outbound:
      external:
        - host: '{{{decorator-external-url}}}'
      rules:
        - application: min-side-arbeidsgiver-api
          namespace: arbeidsgiver
        - application: min-side-arbeidsgiver-api
          namespace: fager
        - application: notifikasjon-bruker-api
          namespace: fager

