apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ditt-nav-arbeidsgiver
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/ditt-nav-arbeidsgiver:bruk-start.sh_57
  team: teamtag
  port: 3000
  ingresses:
    - https://arbeidsgiver-q.nav.no/ditt-nav-arbeidsgiver
  liveness:
    path: /ditt-nav-arbeidsgiver/internal/isAlive
    initialDelay: 20
  readiness:
    path: /ditt-nav-arbeidsgiver/internal/isReady
    initialDelay: 20
  vault:
    enabled: true
  env:
    - name: API_GATEWAY
      value: https://api-gw-q1.oera.no
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: LOGIN_URL
      value: https://loginservice-q.nav.no/login?redirect=https://arbeidsgiver-q.nav.no/ditt-nav-arbeidsgiver