apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
    name: demo-prodlik-min-side-arbeidsgiver
    namespace: fager
    labels:
        team: fager
spec:
    image: { { image } }
    ingresses:
        - https://arbeidsgiver.ekstern.dev.nav.no/min-side-arbeidsgiver
    liveness:
        path: /min-side-arbeidsgiver/internal/isAlive
        initialDelay: 20
    readiness:
        path: /min-side-arbeidsgiver/internal/isReady
        initialDelay: 20
    prometheus:
        enabled: true
        path: /min-side-arbeidsgiver/internal/metrics
    vault:
        enabled: false
    webproxy: false
    idporten:
        enabled: false
    env:
        - name: GIT_COMMIT
          value: { { commit } }
        - name: MILJO
          value: demo
    accessPolicy:
        external:
            - host: fakedings.intern.dev.nav.no
