apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: min-side-arbeidsgiver
  namespace: fager
  labels:
    team: fager
spec:
  image: {{{image}}}
  ingresses:
    - https://arbeidsgiver.intern.dev.nav.no/min-side-arbeidsgiver
  liveness:
    path: /min-side-arbeidsgiver/internal/isAlive
    initialDelay: 20
  readiness:
    path: /min-side-arbeidsgiver/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /min-side-arbeidsgiver/internal/metrics
  vault:
    enabled: false
  webproxy: false
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  envFrom:
    - secret: min-side-ag-frontend
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: LOGIN_URL
      value: https://arbeidsgiver.intern.dev.nav.no/min-side-arbeidsgiver/oauth2/login
    - name: GIT_COMMIT
      value: {{{commit}}}
    - name: MILJO
      value: dev
  accessPolicy:
    outbound:
      external:
        - host: arbeidsgiver-gcp.dev.nav.no
        - host: arbeidsgiver.intern.dev.nav.no
        - host: tiltak-proxy.dev-fss-pub.nais.io
        - host: aareg-innsyn-arbeidsgiver-api.dev-fss-pub.nais.io
        - host: arbeidsplassen.intern.dev.nav.no
        - host: storage.googleapis.com
      rules:
        - application: min-side-arbeidsgiver-api
        - application: notifikasjon-bruker-api
        - application: tiltak-proxy
          namespace: arbeidsgiver
          cluster: dev-fss
        - application: aareg-innsyn-arbeidsgiver-api
          namespace: arbeidsforhold
          cluster: dev-fss
        - application: presenterte-kandidater-api
          namespace: toi
        - application: pam-stillingsregistrering-api
          namespace: teampam
