apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: min-side-arbeidsgiver
  namespace: fager
  labels:
    team: fager
spec:
  image: {{image}}
  ingresses:
    - https://arbeidsgiver.intern.dev.nav.no/min-side-arbeidsgiver
  liveness:
    path: /min-side-arbeidsgiver/internal/isAlive
    initialDelay: 20
  readiness:
    path: /min-side-arbeidsgiver/internal/isReady
    initialDelay: 20
  prometheus:
    enabled: true
    path: /min-side-arbeidsgiver/internal/metrics
  vault:
    enabled: false
  webproxy: false
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  envFrom:
    - secret: min-side-ag-frontend
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: BACKEND_API_URL
      value: http://min-side-arbeidsgiver-api.fager
    - name: LOGIN_URL
      value: https://arbeidsgiver.intern.dev.nav.no/min-side-arbeidsgiver/oauth2/login
    - name: PROXY_LOG_LEVEL
      value: debug
    - name: BRUKER_API_URL
      value: http://notifikasjon-bruker-api.fager.svc.cluster.local
    - name: GIT_COMMIT
      value: {{commit}}
    - name: ARBEIDSFORHOLD_DOMAIN
      value: https://arbeidsforhold.dev.nav.no
    - name: SYKEFRAVAER_DOMAIN
      value: https://sykefravarsstatistikk.intern.dev.nav.no
    - name: MILJO
      value: dev
  accessPolicy:
    outbound:
      external:
        - host: https://arbeidsgiver-gcp.dev.nav.no
      rules:
        - application: min-side-arbeidsgiver-api
        - application: notifikasjon-bruker-api
        - application: tiltaksgjennomforing-api
          namespace: arbeidsgiver
          cluster: dev-fss
        - application: presenterte-kandidater-api
          namespace: toi
