apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: min-side-arbeidsgiver
  namespace: fager
  labels:
    team: fager
spec:
  image: {{{image}}}
  ingresses:
    - https://arbeidsgiver.nav.no/min-side-arbeidsgiver
  liveness:
    path: /min-side-arbeidsgiver/internal/isAlive
  readiness:
    path: /min-side-arbeidsgiver/internal/isReady
  prometheus:
    enabled: true
    path: /min-side-arbeidsgiver/internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  envFrom:
    - secret: min-side-ag-frontend
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: LOGIN_URL
      value: https://arbeidsgiver.nav.no/min-side-arbeidsgiver/oauth2/login
    - name: GIT_COMMIT
      value: {{{commit}}}
    - name: MILJO
      value: prod
    - name: VITE_UMAMI_TRACKING_ID
      value: 3ab987de-cf5c-47a9-a04d-bcf6316f2204
  accessPolicy:
    outbound:
      external:
        - host: arbeidsgiver.nav.no
        - host: tiltak-proxy.prod-fss-pub.nais.io
        - host: aareg-innsyn-arbeidsgiver-api.prod-fss-pub.nais.io
        - host: arbeidsplassen.nav.no
        - host: storage.googleapis.com
        - host: umami.nav.no
      rules:
        - application: min-side-arbeidsgiver-api
        - application: notifikasjon-bruker-api
        - application: tiltak-proxy
          namespace: arbeidsgiver
          cluster: prod-fss
        - application: aareg-innsyn-arbeidsgiver-api
          namespace: arbeidsforhold
          cluster: prod-fss
        - application: presenterte-kandidater-api
          namespace: toi
        - application: pam-stillingsregistrering-api
          namespace: teampam
