name: CICD

on:
    push:
    workflow_dispatch:

jobs:
    bygg:
        name: Bygg
        runs-on: ubuntu-latest
        needs: test
        permissions:
            contents: 'read'
            id-token: 'write'
            packages: 'write'
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  registry-url: https://npm.pkg.github.com/
                  cache: 'npm'

            - name: Installer avhengigheter (client)
              run: npm ci --production --ignore-scripts --no-optional
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

            - name: Installer avhengigheter (server)
              run: npm ci --production --ignore-scripts --no-optional
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
              working-directory: ./server

            - run: npm run lint

            - run: npm run build
              env:
                  PUBLIC_URL: https://cdn.nav.no/fager/min-side-arbeidsgiver/build/

            - uses: nais/docker-build-push@v0
              id: gar-push
              with:
                  team: fager
                  tag: ${{ github.sha }}
                  project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                  identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

            - id: upload
              uses: navikt/frontend/actions/cdn-upload/v1@main
              with:
                  cdn-team-name: fager
                  source: ./build/
                  destination: '/min-side-arbeidsgiver'

            - name: Lag sentry release
              continue-on-error: true
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              run: |
                  npx -p @sentry/cli sentry-cli releases new "${{ github.sha }}"
                  npx -p @sentry/cli sentry-cli releases files "${{ github.sha }}" upload-sourcemaps build/static/js \
                      --url-prefix '~/min-side-arbeidsgiver/static/js'
                  npx -p @sentry/cli sentry-cli releases set-commits --auto "${{ github.sha }}"
                  npx -p @sentry/cli sentry-cli releases finalize "${{ github.sha }}"

    deploy-dev-gcp:
        name: Deploy til dev-gcp
        permissions:
            contents: 'read'
            id-token: 'write'
        runs-on: ubuntu-latest
        timeout-minutes: 3
        if: github.ref == 'refs/heads/master'
        needs: bygg
        steps:
            - name: Sjekk ut kode
              uses: actions/checkout@v3

            - uses: nais/login@v0
              id: login
              with:
                  project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                  identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                  team: fager

            - name: Deploy til dev-gcp
              uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  IMAGE: ${{ steps.login.outputs.registry }}/min-side-arbeidsgiver:${{ github.sha }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais/dev-gcp.yaml
                  PRINT_PAYLOAD: true
                  VAR: commit=${{ github.sha }}

    deploy-prod-gcp:
        name: Deploy til prod-gcp
        if: github.ref == 'refs/heads/master'
        permissions:
            contents: 'read'
            id-token: 'write'
        runs-on: ubuntu-latest
        needs: bygg
        steps:
            - name: Sjekk ut kode
              uses: actions/checkout@v3
            - uses: nais/login@v0
              id: login
              with:
                  project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                  identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                  team: fager
            - name: Deploy til prod-gcp
              uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  IMAGE: ${{ steps.login.outputs.registry }}/min-side-arbeidsgiver:${{ github.sha }}
                  CLUSTER: prod-gcp
                  RESOURCE: nais/prod-gcp.yaml
                  PRINT_PAYLOAD: true
                  VAR: commit=${{ github.sha }}

    deploy-prodlik-demo-gcp:
        name: Deploy prod-lik demo
        if: github.ref == 'refs/heads/master'
        permissions:
            contents: 'read'
            id-token: 'write'
        runs-on: ubuntu-latest
        needs: bygg
        steps:
            - name: Sjekk ut kode
              uses: actions/checkout@v3

            - uses: nais/login@v0
              id: login
              with:
                  project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                  identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                  team: fager

            - name: Deploy til labs-gcp
              uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  IMAGE: ${{ steps.login.outputs.registry }}/min-side-arbeidsgiver:${{ github.sha }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais/labs-gcp.yaml
                  PRINT_PAYLOAD: true
                  VAR: commit=${{ github.sha }}

    deploy-devlik-demo-gcp:
        name: Deploy dev-lik demo
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
        needs: bygg
        steps:
            - name: Sjekk ut kode
              uses: actions/checkout@v3

            - uses: nais/login@v0
              id: login
              with:
                  project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
                  identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
                  team: fager

            - name: Deploy til labs-gcp
              uses: nais/deploy/actions/deploy@v1
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  IMAGE: ${{ steps.login.outputs.registry }}/min-side-arbeidsgiver:${{ github.sha }}
                  CLUSTER: dev-gcp
                  RESOURCE: nais/experimental-labs-gcp.yaml
                  PRINT_PAYLOAD: true
                  VAR: commit=${{ github.sha }}
